# Generated by Django 6.0 on 2026-01-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Время первой отправки"),
                ),
                (
                    "end_time",
                    models.DateTimeField(verbose_name="Время окончания отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершена"),
                            ("created", "Создана"),
                            ("started", "Запущена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=255,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Введите текст письма", verbose_name="Тело письма"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email получателя",
                        max_length=255,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Полное имя получателя",
                        max_length=255,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о получателе",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("error", "Ошибка")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="clients.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог рассылки",
                "verbose_name_plural": "Логи рассылок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="clients.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailings",
                to="clients.recipient",
                verbose_name="Получатели",
            ),
        ),
    ]
